name: Tag Release
on:
  create:
    branches:
      - release/**
      - '!hotfix/**'

jobs:
  tag:
    if: contains(github.ref, 'release')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@altracio'

      - name: Setup git
        run: |
          git config user.name ${GITHUB_ACTOR}
          git config user.email "<>"

      - name: Extract tag from ref
        id: ref_version
        run: echo "::set-output name=VALUE::${GITHUB_REF:19}"

      - name: Extract package version
        id: pkg_version
        run: |
          echo 'pkg_version<<EOF' >> $GITHUB_ENV
          node -pe "require('./package.json').version" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Bump version
        run: |
          npm version ${GITHUB_REF:19} --allow-same-version

      - name: Build changelog
        id: build_changelog
        run: |
          echo 'pkg_changelog<<EOF' >> $GITHUB_ENV
          git log HEAD ^${{ env.pkg_version }} --pretty=%s >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Git push
        run: |
          git tag ${GITHUB_REF:19}
          git push --no-verify origin ${GITHUB_REF:11}
          git push --no-verify origin tag ${GITHUB_REF:19}

      - name: Merge releases into master
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Merge release ${{ steps.ref_version.outputs.VALUE }} into master"
          pr_body: This PR was created by a workflow
          pr_label: git-flow

      - name: Merge releases into develop
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Merge release ${{ steps.ref_version.outputs.VALUE }} into develop"
          pr_body: This PR was created by a workflow action
          pr_label: git-flow

      - name: Create release
        id: create_release
        uses: zendesk/action-create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.ref_version.outputs.VALUE }}
          body: ${{ env.pkg_changelog }}
          tag_schema: semantic
